# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cad930a25ee40755ebcfe550b83e02228e8079d7ad54945ec195096e9bc1b9982ef6377abb760490d280c7dc4c44706c4c3054ec007ed0a9b8dabc117d87db78

test:
  secret_key_base: d80f2c83d5d7b241adc933e977261ced38bec806639d460f5cd5c7256f2c0fb86a33a3a917b817c21f859812121896de1d9f7a0ce35edd9375051bc125361fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
